export const ROUND_CONFIG = {
  readyStableMs: 500,
  autoStartDelayMs: 750,
  countdownMs: 3000,
  countdownTickMs: 1000,
  ponDisplayMs: 250,
  prePonObservationMs: 800,
  postPonDeadlineMs: 1200,
  postCommitConfirmationMs: 200,
  gestureStableMs: 120,
  changedGestureStableMs: 150,
  minStableSamples: 3,
  minGestureScore: 0.65,
  minAssignmentConfidence: 0.5,
  centralAmbiguityHalfWidth: 0.1,
  minimumHandSeparation: 0.12,
  crossingCostMargin: 0.04,
  workerInitTimeoutMs: 10000,
  inferenceIntervalMs: 50,
  minHandDetectionConfidence: 0.5,
  minHandPresenceConfidence: 0.5,
  minHandTrackingConfidence: 0.5,
  modelGestureScoreThreshold: 0.6,
  modelOverrideScore: 0.82,
  landmarkExtensionRatio: 0.14,
  expectedHandLandmarks: 21,
  paperMinExtendedFingers: 4,
  rockMaxExtendedFingers: 1,
  paperLandmarkScoreMax: 0.9,
  paperLandmarkScoreBase: 0.58,
  paperLandmarkScorePerFinger: 0.08,
  scissorsLandmarkScore: 0.76,
  rockLandmarkScoreMax: 0.86,
  rockLandmarkScoreBase: 0.66,
  rockLandmarkScorePerClosedFinger: 0.05,
  unknownLandmarkScore: 0.35,
  blendedGestureScoreMax: 0.99,
  blendedGestureAgreementBonus: 0.12,
  playerRoiSplitX: 0.5,
  darkBrightnessThreshold: 45,
  brightBrightnessThreshold: 220,
  diagnosticsWindowMs: 1000,
  maxObservationBuffer: 240,
  lowFpsWindowsBeforeReduction: 3,
  reducedVideoWidth: 480,
  reducedVideoHeight: 360,
  reviewDelayMs: 200,
  likelyLateDelayMs: 350,
  minimumInferenceFps: 10,
  recommendedInferenceFps: 15,
} as const;
export type RoundConfig = { [Key in keyof typeof ROUND_CONFIG]: number };

export const SENSITIVITY_CONFIGS = {
  strict: {
    ...ROUND_CONFIG,
    minGestureScore: 0.7,
    reviewDelayMs: 150,
    likelyLateDelayMs: 300,
  },
  standard: ROUND_CONFIG,
  lenient: {
    ...ROUND_CONFIG,
    minGestureScore: 0.6,
    reviewDelayMs: 250,
    likelyLateDelayMs: 450,
  },
} satisfies Record<string, RoundConfig>;
